apiVersion: v1
kind: Service
metadata:
  name: my-go-app-service
  namespace: my-go-app
  labels:
    app: my-go-app
spec:
  type: NodePort
  selector:
    app: my-go-app  # must match the pod label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080