name: Build and Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'helm/**'

jobs:
  # Build and Test
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        run: go build -v -o my-go-app

      - name: Test
        run: go test ./...

  # Build and Push Docker Image
  push:
    name: Build and Push Docker Image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/my-go-app:${{ env.SHORT_SHA }}
          build-args: --no-cache

  deploy:
    name: Update Helm Values
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Install yq
        run: sudo apt-get install -y yq

      - name: Update Helm values
        run: |
          cd helm/my-go-app-chart
          yq eval '.image.repository = "${{ secrets.DOCKERHUB_USERNAME }}/my-go-app"' -i values.yaml
          yq eval '.image.tag = "${{ env.SHORT_SHA }}"' -i values.yaml

      - name: Commit and push updated values
        run: |
          git config --global user.name 'queensley200'
          git config --global user.email 'kissesndhuggz@gmail.com'
          git add helm/my-go-app-chart/values.yaml
          git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
          git push
